http.enabled: true
http.port: 5066
http.host: 0.0.0.0

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

monitoring.enabled: false

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${PASSWORD}"
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/usr/share/metricbeat/certificates/ca/ca.crt"]

setup.dashboards.enabled: true

setup.kibana:
  host: "https://kibana:5601"
  username: "elastic"
  password: "${PASSWORD}"
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/usr/share/metricbeat/certificates/ca/ca.crt"]

metricbeat.modules:
- module: kibana
  metricsets:
    - stats
  xpack.enabled: true
  period: 10s
  hosts: ["https://kibana:5601"]
  username: "remote_monitoring_user"
  password: "${RPASSWORD}"
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/usr/share/metricbeat/certificates/ca/ca.crt"]
- module: docker
  metricsets: ["container","cpu","diskio","healthcheck","info","image","memory","network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ["logstash:9600"]
 

- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://metricbeat:5066"]
  xpack.enabled: true
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/usr/share/metricbeat/certificates/ca/ca.crt"]

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
  username: "remote_monitoring_user"
  password: "${RPASSWORD}"
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/usr/share/metricbeat/certificates/ca/ca.crt"]
